### ISSUE TITLE
usage with next-compose-plugins?

### ISSUE THREAD

**Issue by ljosberinn** [newhighsco/next-plugin-svgr#95]
Hi, thank you for this package, seems to be the most configurable of the 5 possibilities out there.

I had issues integrating it with [next-compose-plugins](https://github.com/cyrilwanner/next-compose-plugins), would you mind adding an example if its currently possible, or supporting it alternatively?

Currently, `svgrOptions` is internally always undefined when passed to `next-plugin-svgr` through `withPlugins` from `next-compose-plugins`. Tried different approaches for a while, but ended up inlining your plugin.

**Comment by benedfit** [comment]
Hi, thanks for using the plugin. I'm using it as follows https://github.com/newhighsco/press-start/blob/master/next.config.js, but I needed to double check it's actually working as expected if you are having trouble. I'll check and get back to you

**Comment by benedfit** [comment]
Yup, totally not working as I was expecting it. I'll get a patch sorted

**Comment by benedfit** [comment]
v2.0.0 released to resolve this issue - https://github.com/newhighsco/next-plugin-svgr/releases/tag/v2.0.0

Went ahead and published a breaking change for anyone who may be inlining the plugin in it's current state
